trigger:
  branches:
    include:
      - '*'
    exclude:
      - gh-pages

pr:
  - master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
  - script: |
      git config --global core.autocrlf false
      git config --global core.eol lf
    displayName: Configure LF for Windows

  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '13.x'
      checkLatest: true
    displayName: 'Install Node.js'

  - bash: npm ci
    displayName: Install Dependencies

  - bash: npm run build
    displayName: Build

  - bash: |
      set -e
      /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
      disown -ar
      echo "Started xvfb"
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: Start xvfb

  - bash: npm run e2e
    displayName: Run End-To-End Tests
    condition: always()
    env:
      DISPLAY: :10

  - bash: npm test
    displayName: Run Unit Tests
    condition: always()
    env:
      DISPLAY: :10
#
